### ISSUE TITLE
Hi, 当我执行 `npm run build`时发生下发错误，可能是因为什么导致的？

### ISSUE THREAD

**Issue by viktyz** [jinyang1994/Blog#1]
Hi, 当我执行 `npm run build`时发生下发错误，可能是因为什么导致的？

`> blog@1.0.0 build /Users/vTest/Desktop/TBLog/Blog
> node build/build.js

fs.js:895
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'static/posts'
    at Object.fs.mkdirSync (fs.js:895:18)
    at create (/Users/vTest/Desktop/TBLog/Blog/build/create-posts-json.js:52:8)
    at Object.<anonymous> (/Users/vTest/Desktop/TBLog/Blog/build/create-posts-json.js:59:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)`

**Comment by liujinyang1994** [comment]
可能是因为我的static 目录没有上传，你可以先手动的在根目录下面创建一个static 文件夹就可以解决这个问题，后续我将会改进这个问题。下版本预计会增加代码高亮等完善性的功能，请保持关注，谢谢。

**Comment by JH46666** [comment]
怎么运行呢

**Comment by liujinyang1994** [comment]
@JH46666 npm run dev
